// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Poppins, Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import CookingAssistant from "./components/ai/CookingAssistant";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Recipe-Hub ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <ToastContainer />
        {/* Self-gating: renders null unless a user is signed in, so one mount
            here covers the whole app without appearing on the auth pages. */}
        <CookingAssistant />
      </body>
    </html>
  );
}
